Repository SDprojects8/OnlineStoreWebScraping, pull requests merged in 2021-01, with the labels that each got.

#4 Interactive
  scripts/FlipkartDeals_Interactive_csvNotWorking.py
Labels: duplicate

#3 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#8 Update review in Headphones and Bakeware
  data/FlipkartBakeware.xlsx
  data/FlipkartHeadPhone.xlsx
  scripts/FlipkartDeals_Bakeware.py
  scripts/FlipkartDeals_HeadPhones.py
Labels: enhancement

#9 Initialize README for Github Pages + print line numbers
  README.md
  data/FlipkartHeadPhone.xlsx
  scripts/FlipkartDeals_Interactive.py
Labels: enhancement
